export const ADD_TODO_DATA = "ADD_TODO_DATA";
export const ADD_MODAL_STATUS = "ADD_MODAL_STATUS";
export const SET_TODO_DATA="SET_TODO_DATA"
export const EDIT_MODAL_STATUS = "EDIT_MODAL_STATUS";
export const EDIT_TODO_DATA="EDIT_TODO_DATA"