export const ADD_TODO_DATA = "ADD_TODO_DATA";
export const ADD_MODAL_STATUS = "ADD_MODAL_STATUS";
export const DELETE_TODO_DATA="DELETE_TODO_DATA"
export const ADD_COMPLETE_TODO_DATA="ADD_COMPLETE_TODO_DATA"
export const EDIT_MODAL_STATUS = "EDIT_MODAL_STATUS";
export const SET_TODO_DATA="SET_TODO_DATA"
export const EDIT_TODO_DATA="EDIT_TODO_DATA"
export const RESET_TODO="RESET_TODO"

export const HANDLE_MULTIPLE_DELETE_DATA="HANDLE_MULTIPLE_DELETE_DATA"
export const HANDLE_MULTIPLE_COMPLETE_DATA="HANDLE_MULTIPLE_COMPLETE_DATA"
export const HANDLE_MULTIPLE_COPY_DATA="HANDLE_MULTIPLE_COPY_DATA"
export const ADD_TODO_DATA_FROM_UNCOMPLETE="ADD_TODO_DATA_FROM_UNCOMPLETE"
export const DELETE_FROM_COMPLETE_DATA="DELETE_FROM_COMPLETE_DATA"
export const ALL_COMPLETED_IDS="ALL_COMPLETED_IDS"